### ISSUE TITLE
A github actions example to extract issues of the repo itself

### ISSUE THREAD

**Issue by 0ut0fcontrol** [mattduck/gh2md#11]
Thank you for your great work.

I add my github actions example here, in case someone needs it.

it backups all issues every days.

Because it only backup the issues belong to the repository that contains this workflow. It do not limit by GitHub API rate.
```console
# gh2md log:
...
Exported 28 issues
Writing to file: issues.md
Github API rate limit: {u'reset': 1594884997, u'limit': 15000, u'remaining': 15000}
Done.
```

```yaml
# .github/workflows/issues2md.yml
name: Issues2Markdown
on:
  push:
  schedule:
    # every day
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Backup github issues to a markdown file.
      run: |
        pip install wheel
        pip install --user gh2md
        $HOME/.local/bin/gh2md $GITHUB_REPOSITORY issues.md --token ${{ secrets.GITHUB_TOKEN }}
        git add issues.md
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Backup all issues into issues.md" -a
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.extract_branch.outputs.branch }}

```
